# Many thanks to the New York Times for their list:
# https://www.nytimes.com/interactive/2016/01/28/upshot/donald-trump-twitter-insults.html

FIRST_TRUMPIAN_WORDS = [
    'fake',
    'rambiling',
    'unwatchable',
    'clown',
    'rigged',
    'nasty',
    'weak',
    'stupid',
    'lightweight',
    'lazy',
    'unfair',
    'dishonest',
    'ridiculous',
    'little',
    'crooked',
    'hostile',
    'jilted',
    'terrible'
]

SECOND_TRUMPIAN_WORDS = [
    'totally-phoney',
    'already-proven-false',
    '100-percent-fabricated',
    'total-mess',
    'not-very-bright',
    'basket-case'
]

THIRD_TRUMPIAN_WORDS = [
    'dope',
    'joke',
    'puppet',
    'failed Jeb Bushy',
    'dummy',
    'loser',
    'moron',
    'clown with zero credibility',
    'Bush plant',
    'dumbest and worst candidates in the history of Republican politics',
    'weak candidate'
]

FORTH_TRUMPIAN_ADDITIONS = [
    'with bad intentions',
    'with no credibility',
    'with so little touch for politics',
    'who failed badly',
    'who knowingly writes lies'
]

# Many thanks to Jerry Maguire and the person that made this web page:
# http://www.pangloss.com/seidel/shake_rule.html

FIRST_SHAKESPEAREAN_WORDS = [
    'artless',
    'bawdy',
    'beslubbering',
    'bootless',
    'churlish',
    'cockered',
    'clouted',
    'craven',
    'currish',
    'dankish',
    'dissembling',
    'droning',
    'errant',
    'fawning',
    'fobbing',
    'froward',
    'frothy',
    'gleeking',
    'goatish',
    'gorbellied',
    'impertinent',
    'infectious',
    'jarring',
    'loggerheaded',
    'lumpish',
    'mammering',
    'mangled',
    'mewling',
    'paunchy',
    'pribbling',
    'puking',
    'puny',
    'qualling',
    'rank',
    'reeky',
    'roguish',
    'ruttish',
    'saucy',
    'spleeny',
    'spongy',
    'surly',
    'tottering',
    'unmuzzled',
    'vain',
    'venomed',
    'villainous',
    'warped',
    'wayward',
    'weedy',
    'yeasty'
]

SECOND_SHAKESPEAREAN_WORDS = [
    'base-court',
    'bat-fowling',
    'beef-witted',
    'beetle-headed',
    'boil-brained',
    'clapper-clawed',
    'clay-brained',
    'common-kissing',
    'crook-pated',
    'dismal-dreaming',
    'dizzy-eyed',
    'doghearted',
    'dread-bolted',
    'earth-vexing',
    'elf-skinned',
    'fat-kidneyed',
    'fen-sucked',
    'flap-mouthed',
    'fly-bitten',
    'folly-fallen',
    'fool-born',
    'full-gorged',
    'guts-griping',
    'half-faced',
    'hasty-witted',
    'hedge-born',
    'hell-hated',
    'idle-headed',
    'ill-breeding',
    'ill-nurtured',
    'knotty-pated',
    'milk-livered',
    'motley-minded',
    'onion-eyed',
    'plume-plucked',
    'pottle-deep',
    'pox-marked',
    'reeling-ripe',
    'rough-hewn',
    'rude-growing',
    'rump-fed',
    'shard-borne',
    'sheep-biting',
    'spur-galled',
    'swag-bellied',
    'tardy-gaited',
    'tickle-brained',
    'toad-spotted',
    'unchin-snouted',
    'weather-bitten'
]

THIRD_SHAKESPEAREAN_WORDS = [
    'apple-john',
    'baggage',
    'barnacle',
    'bladder',
    'boar-pig',
    'bugbear',
    'bum-bailey',
    'canker-blossom',
    'clack-dish',
    'clotpole',
    'coxcomb',
    'codpiece',
    'death-token',
    'dewberry',
    'flap-dragon',
    'flax-wench',
    'flirt-gill',
    'foot-licker',
    'fustilarian',
    'giglet',
    'gudgeon',
    'haggard',
    'harpy',
    'hedge-pig',
    'horn-beast',
    'hugger-mugger',
    'joithead',
    'lewdster',
    'lout',
    'maggot-pie',
    'malt-worm',
    'mammet',
    'measle',
    'minnow',
    'miscreant',
    'moldwarp',
    'mumble-news',
    'nut-hook',
    'pigeon-egg',
    'pignut',
    'puttock',
    'pumpion',
    'ratsbane',
    'scut',
    'skainsmate',
    'strumpet',
    'varlot',
    'vassal',
    'whey-face',
    'wagtail'
]